name: CI SQA Rails 8

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Ruby 3.3 (Requerido para Rails 8)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # <--- AQUÍ ESTABA EL DETALLE
          bundler-cache: false

      - name: Instalar librerías Linux
        run: sudo apt-get install -y libsqlite3-dev yaml-lint

      - name: Limpiar conflictos de Windows
        run: |
          # Borramos el candado de versiones de tu PC para crear uno de Linux
          rm -f Gemfile.lock
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Preparar Base de Datos
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Ejecutar Pruebas
        run: |
          # Si tienes RSpec corre esto, si no, corre Minitest
          if [ -d "spec" ]; then
            bundle exec rspec
          else
            bundle exec rails test
          fi
